### ISSUE TITLE
AnimationControllerX with manual config doesen't update state   

### ISSUE THREAD

**Issue by nikitattt** [felixblaschke/simple_animations#15]
Hello!

Created manually `AnimationControllerX` instance in your sample app and found that widget state does not change during animation ticks. I had to externally update state to see any changes. Didn't find any data related to that in docs. I know that I can use `AnimationControllerMixin`, but what I can do if I want to have distinct controllers?

**Comment by felixblaschke** [comment]
Hello! Sorry for my late response. I didn't realized I need to watch my own project on github in order to receive notification.

Nevertheless you were right. I missed one important line in my documentation:
``controller.addListener(() => setState(() {}));``

Since AnimationControllerX acts the same as the traditional AnimationController you'll need to tell it that the state of the widget has changed.

Thank you for your feedback. I updated the documentation.
