### ISSUE TITLE
MultiTrackTween not refreshed after rebuild

### ISSUE THREAD

**Issue by Deeplightened** [felixblaschke/simple_animations#17]
Hello, I have an issue with ControlledAnimation and MultiTrackTween : I want to do a gradient animation with it and trigger the animation when I change a page in my application. The animation is different for each page, so I change the MultiTrackTween instance at every widget rebuild. But when I rebuild my widget and the contained ControlledAnimation, tweens are not updated.

The code : 
```
final List<List<Color>> states = [
  [Color(0xFF9768BF), Color(0xFF4DB9B5)],
  [Color(0xFF4DB9B5), Color(0xFF77A338)],
  [Color(0xFF77A338), Color(0xFFC68B1C)],
  [Color(0xFFC68B1C), Color(0xFF9768BF)]
];

 Widget createAnimation(int page) {

    final duration = Duration(milliseconds: 200);

    int previousPage = page - 1;
    if (previousPage < 0) previousPage = 3;

    MultiTrackTween tweens = MultiTrackTween([
      Track("colorStart").add(
          duration, ColorTween(begin: states[previousPage][0], end: states[previousPage][1])),
      Track("colorEnd").add(
          duration, ColorTween(begin: states[page][0], end: states[page][1])),
    ]);

    return ControlledAnimation(
      playback: Playback.START_OVER_FORWARD,
      duration: tweens.duration,
      tween: tweens,
      builder: (context, animation) {
        final start = animation["colorStart"];
        final end = animation["colorEnd"];

        return createBackgroundContainer(start, end);
      },
    );
  }
  
  Widget createBackgroundContainer(Color start, Color end) => Container(
        decoration: BoxDecoration(
            gradient: LinearGradient(
                colors: [start, end],
                begin: Alignment.bottomLeft,
                end: Alignment.topRight)),
      );
```

Thank you in advance for your time

**Comment by felixblaschke** [comment]
Hello Deeplightened,

yes, in your code the `ControlledAnimation` widget isn't updating because it get's recycled by Flutter. Flutter is very clever. Instead of recreating already created and ready-layouted widgets it reuses them whenever it can.

In your scenario you need to tell Flutter that is must not recycle the `ControlledAnimation` widget. To do so, you'll need to set a key. (btw that works for every widget)

For your case the best is to use a `LabeledGlobalKey`. You can pass a string as a unique identified. See:
```dart
ControlledAnimation(
      key: LabeledGlobalKey("ControlledAnimation_Page_$page"),
     // ...
)
```

The Flutter devs made a nice video about using keys and widget recycling: https://www.youtube.com/watch?v=kn0EOS-ZiIc

I made a working app from your snippet for you: https://gist.github.com/felixblaschke/ae31c6d0dbbfe4bf10752bd6f2f5bab8

Also watch out to use `builderWithChild` to avoid recreating your page content widgets whenever the animation redraws. This could lead to some laggy behavior when switching pages.

I hope this helps you. I also like your animation. Looks amazing!

**Comment by Deeplightened** [comment]
Wow :O, thank you for all theses informations ! I'm new to Flutter indeed, I didn't knew there was such a system behind.

And also thank you for your reactivity :) !

**Comment by felixblaschke** [comment]
No problem. Glad I could help. Have much fun animating 🌝

**Comment by nicoroy2561** [comment]
thank you @felixblaschke, as this solved my problem too. 
When you have time, please add a note somewhere in the documentation (at least for ControlledAnimation) so it's easier to find.

**Comment by felixblaschke** [comment]
I didn't thought that is such a big problem. The topic keys is actually the first chapter in the Flutter documentation: https://flutter.dev/docs/development/ui/widgets-intro#keys

**Comment by nicoroy2561** [comment]
I've been using Flutter for a month now and just started using keys yesterday. For the most part I think most people won't need them at all - again, how often will you really find yourself applying a different animation on a widget based on context - maybe once per app at most. And even then, I found another workaround (having set values and using a ControlledAnimation ranging 0.0 to 1.0, then multiplied for those said values). Might be something only newbies (as I am) will find themselves struggling with, but then adding a note (or even just a link to this issue) somewhere within the documentation would've helped me find this sooner (I was about to open another same issue, but GitHub suggested me this).

Either way, thank you for this great plugin. It really makes animations damn simple to make & handle, and I am very grateful to you for this.

**Comment by felixblaschke** [comment]
Alright. I added documentation note on using `key` in my next iteration of simple_animations:
https://github.com/felixblaschke/sa_stateless_animation#using-keys
