### ISSUE TITLE
Use of enum in Track class instead of String for key

### ISSUE THREAD

**Issue by AntonBlomstrom** [felixblaschke/simple_animations#25]
Hi! First time writing an issue, so please forgive me if I'm doing something wrong.

Just wanted to suggest using enums for the key/name in the Track class. I think it'd improve how you refactor the animation code. Searching for enum usage rather than strings for example.

I did a quick swap here and it seems to work alright:
![image](https://user-images.githubusercontent.com/39986991/77829656-adafe000-7123-11ea-9a76-3e8796cc0fa5.png)

I'd be happy to do a pull request and change it. Of course, it'd be a breaking change.. So I understand if you rather not.

Awesome package either way, so thank you for making it!

**Comment by felixblaschke** [comment]
Interesting suggestion, i will check that out :-)

**Comment by AntonBlomstrom** [comment]
Thanks!

One could also swap the map out for a list with 
`Animate.values.length` for the list length and
`Animate.height.index` for indexing that list.

Although I doubt that'd be worth the hassle. Might even introduce overhead in other places, like iterating through that list.

**Comment by felixblaschke** [comment]
Today I played around with your approach. It's a very good hint but I am generally not satisfied with the way parts of simple_animation work. I am currently think about a V2 with more type-safe and modular approach. This project has been grown a lot since last year to a 99% score library.

Adding enum would break others people code. I don't want that. Loosing the name parameter type of a `Track` from `String` to `dynamic` would confuse people.

Meanwhile you can use static classes as a work around until I have figured out a permanent solution:

```dart
class TweenProps {
  static String width = "width";
  static String height = "height";
}
```

```dart
final _tween = MultiTrackTween([
  Track(TweenProps.width).add(
    Duration(milliseconds: 1000),
    Tween(begin: 0.0, end: 100.0),
  ),
  Track(TweenProps.height).add(
    Duration(milliseconds: 1000),
    Tween(begin: 0.0, end: 100.0),
  )
]);
```

**Comment by felixblaschke** [comment]
I added the first approach (based on your enum solution) as a package module:
https://pub.dev/packages/sa_multi_tween

Feel free to review it :-)

**Comment by AntonBlomstrom** [comment]
Nicely done! I will give it a go when I get back to writing more on my website ^^
Sorry for the delay as well, I would've closed the issue if I had noticed your replies earlier.

Either way, thank you for implementing it!
