### ISSUE TITLE
Question: incorporating svg/png into bubble particle system -- performance issues?

### ISSUE THREAD

**Issue by dougproctor** [felixblaschke/simple_animations#47]
Hi @felixblaschke,

I am interested in incorporating your particle animation package into my current Flutter project -- specifically, I'm hoping to use semi-transparent user contact images (svg/png) as the reference background for bubbles. I'd probably aim to have have O(10) bubbles on the device screen at a time, with new bubbles selecting contact photos at random. The app use case is essentially a chat app, and this functionality will be incorporated as a sort of dynamic loading screen to give the user a sense for which of their contacts they might be matching with after a matching process is completed. All of my backend work is currently in Firebase / Cloud Functions, and after a quick glance at your repo, looked like doing something like this should not be too complicated.  

That said, before I dive in I was curious as to whether you had previously tried this sort of thing with your particle animation package, and/or whether you would expect there to be any significant performance (or other) challenges associated with doing this sort of thing?

Thanks!

**Comment by felixblaschke** [comment]
If you using https://pub.dev/packages/simple_animations/example#bubbles as the base it will have no worse performance aspect since all textures (png/svg) are already painted. Flutter uses heavy compositing (transformation on GPU) to create an image. You should be fine with it.

Instead of drawing circles it just circles image bitmaps.
